// Sends the emails generated by the weekly session job.
import nodemailer from "nodemailer";

let transporterPromise;

function getTransporter() {
  if (!transporterPromise) {
    transporterPromise =
      process.env.MAIL_TRANSPORT === "ethereal"
        ? nodemailer.createTestAccount().then((account) =>
            nodemailer.createTransport({
              host: account.smtp.host,
              port: account.smtp.port,
              secure: account.smtp.secure,
              auth: { user: account.user, pass: account.pass },
            }),
          )
        : Promise.resolve(nodemailer.createTransport({ jsonTransport: true }));
  }
  return transporterPromise;
}

// Returns { previewUrl } — previewUrl is null unless MAIL_TRANSPORT=ethereal.
export async function sendGeneratedEmail({ from, to, subject, text }) {
  const transporter = await getTransporter();
  const info = await transporter.sendMail({ from, to, subject, text });
  return { previewUrl: nodemailer.getTestMessageUrl(info) || null };
}
